const Role = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  USER: "USER",
  DEVELOPER: "DEVELOPER",
  INTERNAL_CLIENT: "INTERNAL_CLIENT",
  EXTERNAL_CLIENT: "EXTERNAL_CLIENT",
};

export default Role;
